### ISSUE TITLE
haikunator.default() instead of haikunator()

### ISSUE THREAD

**Issue by ChristianSch** [Atrox/haikunatorjs#6]
Hi!

I think that either your export setting or the documentation is off, as I could not use that:
```
var haikunate = require('haikunator'),
    name = haikunate();
```

but had to use this instead:
```
var haikunate = require('haikunator').default,
    name = haikunate();
```

**Comment by Atrox** [comment]
Thank you for letting me know. I just published 1.2.1. Should be fixed now.
